name: Deploy to staging
on:
  push:
    branches: [main]

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest
    steps:
      - run: echo "hi there"
