name: Deploy to staging
on:
  push:
    branches: [production]

jobs:
  redeploy_everything:
    name: Deploying everything to the staging cluster
    runs-on: ubuntu-latest
    steps:
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa ubuntu@65.0.107.210 << 'EOF'
          set -e
          cd devops/ && 
          git reset --hard origin/main &&
          git clean -fd && git pull origin production &&
          export PATH=/home/ubuntu/.nvm/versions/node/v22.17.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin &&
          npm install -g pnpm &&
          pnpm install &&
          pnpm run build &&
          pm2 restart fe-server &&
          pm2 restart http-server &&
          pm2 restart ws-server &&
          EOF
